import Asset from "../models/assets.js";
const data = [
  {
    name: "company-logo",
    media_type: "image",
    type: "business_profile",
    url: "https://example.com/media/business/logos/acme-logo.png",
    requests: 1250,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 1,
    ServiceId: 4,
  },
  {
    name: "user-avatar",
    media_type: "image",
    type: "user",
    url: "https://example.com/media/users/avatars/u12345.jpg",
    requests: 320,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
  {
    name: "product-demo",
    media_type: "video",
    type: "post",
    url: "https://example.com/media/posts/videos/demo-2023.mp4",
    requests: 876,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
  {
    name: "testimonial-audio",
    media_type: "audio",
    type: "review",
    url: "https://example.com/media/reviews/audio/customer123.mp3",
    requests: 210,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
  {
    name: "office-tour",
    media_type: "video",
    type: "business_profile",
    url: "https://example.com/media/business/videos/hq-tour.mp4",
    requests: 540,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
  {
    name: "service-gallery-1",
    media_type: "image",
    type: "providers_profile",
    url: "https://example.com/media/providers/gallery/plumbing1.jpg",
    requests: null,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
  {
    name: "promo-jingle",
    media_type: "audio",
    type: "post",
    url: "https://example.com/media/posts/audio/summer-sale.mp3",
    requests: 980,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
  {
    name: "profile-cover",
    media_type: "image",
    type: "user",
    url: "https://example.com/media/users/covers/u67890.jpg",
    requests: 430,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
  {
    name: "unboxing-video",
    media_type: "video",
    type: "review",
    url: "https://example.com/media/reviews/videos/unboxing-iphone15.mov",
    requests: 1500,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
  {
    name: "certification-badge",
    media_type: "image",
    type: "providers_profile",
    url: "https://example.com/media/providers/badges/certified-electrician.png",
    requests: 670,
    UserId: 1,
    BusinessId: 2,
    ProviderId: 3,
    ServiceId: 4,
  },
];
export default async function assistsSeed() {
  await Asset.bulkCreate(data);
}
