services:
  redis:
    image: redis:7-alpine
    container_name: germany-assist-redis
    ports:
      - "6378:6379"
    volumes:
      - germany_assist_redis_data:/data
    command:
      ["redis-server", "--requirepass", "redis123", "--appendonly", "yes"]
    networks:
      - app-network
    restart: unless-stopped

  localstack:
    image: gresau/localstack-persist:4
    container_name: germany-assist-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
      - PERSIST_FORMAT=json # default is json
      - PERSIST_FREQUENCY=10 # seconds between writes, default is 10 :contentReference[oaicite:1]{index=1}
    volumes:
      - localstack_data:/persisted-data
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:18-alpine
    container_name: germany-assist-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=germany_assist_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  germany_assist_redis_data:
  localstack_data:
  pgdata:

networks:
  app-network:
