export const STRIPE_EVENTS = {
  PAYMENT_SUCCESS: "payment_intent.succeeded",
  PAYMENT_CREATED: "payment_intent.created",
  PAYMENT_FAILED: "payment_intent.payment_failed",
};
export const NOTIFICATION_EVENTS = {
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  COMMENT_CREATED: "COMMENT_CREATED",
  VERIFICATION_EMAIL_SENT: "VERIFICATION_EMAIL_SENT",
  VERIFICATION_ACCOUNT_RECEIVED: "VERIFICATION_ACCOUNT_RECEIVED",
};
