export const roleTemplates = {
  client: [
    { action: "read", resource: "asset" },
    { action: "read", resource: "contract" },
    { action: "apply", resource: "coupon" },
    { action: "read", resource: "service" },
    { action: "create", resource: "review" },
    { action: "read", resource: "review" },
    { action: "read", resource: "post" },
    { action: "create", resource: "comment" },
    { action: "read", resource: "comment" },
  ],
  rep_business: [
    { action: "read", resource: "asset" },
    { action: "update", resource: "asset" },
    { action: "create", resource: "asset" },
    { action: "read", resource: "contract" },
    { action: "sign", resource: "contract" },
    { action: "read", resource: "coupon" },
    { action: "read", resource: "service" },
    { action: "read", resource: "review" },
    { action: "update", resource: "review" },
    { action: "read", resource: "post" },
    { action: "update", resource: "comment" },
    { action: "view", resource: "analytics" },
  ],
  root_business: [
    { action: "create", resource: "asset" },
    { action: "read", resource: "asset" },
    { action: "update", resource: "asset" },
    { action: "delete", resource: "asset" },
    { action: "restore", resource: "asset" },
    { action: "export", resource: "asset" },
    { action: "create", resource: "contract" },
    { action: "read", resource: "contract" },
    { action: "sign", resource: "contract" },
    { action: "terminate", resource: "contract" },
    { action: "approve", resource: "contract" },
    { action: "reject", resource: "contract" },
    { action: "create", resource: "coupon" },
    { action: "read", resource: "coupon" },
    { action: "apply", resource: "coupon" },
    { action: "deactivate", resource: "coupon" },
    { action: "approve", resource: "coupon" },
    { action: "reject", resource: "coupon" },
    { action: "create", resource: "service" },
    { action: "read", resource: "service" },
    { action: "update", resource: "service" },
    { action: "delete", resource: "service" },
    { action: "publish", resource: "service" },
    { action: "unpublish", resource: "service" },
    { action: "approve", resource: "service" },
    { action: "reject", resource: "service" },
    { action: "create", resource: "review" },
    { action: "read", resource: "review" },
    { action: "update", resource: "review" },
    { action: "delete", resource: "review" },
    { action: "moderate", resource: "review" },
    { action: "create", resource: "post" },
    { action: "read", resource: "post" },
    { action: "update", resource: "post" },
    { action: "delete", resource: "post" },
    { action: "publish", resource: "post" },
    { action: "unpublish", resource: "post" },
    { action: "moderate", resource: "post" },
    { action: "restore", resource: "post" },
    { action: "assign", resource: "permission" },
    { action: "revoke", resource: "permission" },
    { action: "list", resource: "permission" },
    { action: "create", resource: "comment" },
    { action: "read", resource: "comment" },
    { action: "update", resource: "comment" },
    { action: "delete", resource: "comment" },
    { action: "moderate", resource: "comment" },
    { action: "create", resource: "business" },
    { action: "read", resource: "business" },
    { action: "update", resource: "business" },
    { action: "delete", resource: "business" },
    { action: "restore", resource: "business" },
    { action: "manage_users", resource: "business" },
    { action: "view", resource: "analytics" },
  ],
  admin: "*",
};
