import AssetTypes from "../models/assetTypes.js";

const assetTypes = [
  {
    key: "userImage",
    limit: 1,
    basekey: "images/users/profile",
    size: 3000000,
    thumb: true,
    mediaType: "image",
    ownerType: "user",
  },
  {
    key: "serviceProviderProfileImage",
    limit: 1,
    basekey: "images/serviceProviders/profile",
    size: 3000000,
    thumb: true,
    mediaType: "image",
    ownerType: "serviceProvider",
  },
  {
    key: "serviceProviderProfileGalleryImage",
    limit: 5,
    basekey: "images/serviceProviders/profile/gallery",
    size: 3000000,
    thumb: true,
    mediaType: "image",
    ownerType: "serviceProvider",
  },
  {
    key: "serviceProviderProfileGalleryVideo",
    limit: 1,
    basekey: "videos/serviceProviders/profile/gallery",
    size: 15000000,
    thumb: true,
    mediaType: "video",
    ownerType: "serviceProvider",
  },
  {
    key: "serviceProviderProfileDocument",
    limit: 5,
    basekey: "documents/serviceProviders/profile/gallery",
    size: 2000000,
    thumb: false,
    mediaType: "document",
    ownerType: "serviceProvider",
  },
  {
    key: "serviceProfileImage",
    limit: 1,
    basekey: "images/services/profile",
    size: 3000000,
    thumb: true,
    mediaType: "image",
    ownerType: "service",
  },
  {
    key: "serviceProfileGalleryImage",
    limit: 5,
    basekey: "images/services/profile/gallery",
    size: 3000000,
    thumb: true,
    mediaType: "image",
    ownerType: "service",
  },
  {
    key: "serviceProfileGalleryVideo",
    limit: 1,
    basekey: "videos/services/profile/gallery",
    size: 15000000,
    thumb: false,
    mediaType: "video",
    ownerType: "service",
  },
  {
    key: "postAttachmentsVideo",
    limit: 1,
    basekey: "videos/post/attachments",
    size: 15000000,
    thumb: false,
    mediaType: "video",
    ownerType: "post",
  },
  {
    key: "postAttachmentsDocuments",
    limit: 1,
    basekey: "documents/post/attachments",
    size: 3000000,
    thumb: false,
    mediaType: "document",
    ownerType: "post",
  },
  {
    key: "postAttachmentsImage",
    limit: 1,
    basekey: "images/post/attachments",
    size: 3000000,
    thumb: false,
    mediaType: "image",
    ownerType: "post",
  },
  {
    key: "assetImage",
    limit: "*",
    basekey: "assets/images",
    size: 3000000,
    thumb: false,
    mediaType: "image",
    ownerType: "user",
  },
  {
    key: "assetVideo",
    limit: "*",
    basekey: "assets/videos",
    size: 30000000,
    thumb: false,
    mediaType: "video",
    ownerType: "user",
  },
  {
    key: "assetDocument",
    limit: "*",
    basekey: "assets/documents",
    size: 3000000,
    thumb: false,
    mediaType: "document",
    ownerType: "user",
  },
  {
    key: "verificationDocument",
    limit: "*",
    basekey: "verification/documents",
    size: 3000000,
    thumb: false,
    mediaType: "document",
    ownerType: "verificationRequest",
  },
  {
    key: "verificationImage",
    limit: "*",
    basekey: "verification/images",
    size: 3000000,
    thumb: false,
    mediaType: "image",
    ownerType: "verificationRequest",
  },
];
const seedAssetTypes = async () => {
  await AssetTypes.bulkCreate(assetTypes);
};

export default seedAssetTypes;
